// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/i64.proto

package gopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type I64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         int64                  `protobuf:"varint,1,opt,name=Field,proto3" json:"Field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I64) Reset() {
	*x = I64{}
	mi := &file_proto_i64_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I64) ProtoMessage() {}

func (x *I64) ProtoReflect() protoreflect.Message {
	mi := &file_proto_i64_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I64.ProtoReflect.Descriptor instead.
func (*I64) Descriptor() ([]byte, []int) {
	return file_proto_i64_proto_rawDescGZIP(), []int{0}
}

func (x *I64) GetField() int64 {
	if x != nil {
		return x.Field
	}
	return 0
}

var File_proto_i64_proto protoreflect.FileDescriptor

var file_proto_i64_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x36, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1b, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x08,
	0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_i64_proto_rawDescOnce sync.Once
	file_proto_i64_proto_rawDescData []byte
)

func file_proto_i64_proto_rawDescGZIP() []byte {
	file_proto_i64_proto_rawDescOnce.Do(func() {
		file_proto_i64_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_i64_proto_rawDesc), len(file_proto_i64_proto_rawDesc)))
	})
	return file_proto_i64_proto_rawDescData
}

var file_proto_i64_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_i64_proto_goTypes = []any{
	(*I64)(nil), // 0: i64
}
var file_proto_i64_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_i64_proto_init() }
func file_proto_i64_proto_init() {
	if File_proto_i64_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_i64_proto_rawDesc), len(file_proto_i64_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_i64_proto_goTypes,
		DependencyIndexes: file_proto_i64_proto_depIdxs,
		MessageInfos:      file_proto_i64_proto_msgTypes,
	}.Build()
	File_proto_i64_proto = out.File
	file_proto_i64_proto_goTypes = nil
	file_proto_i64_proto_depIdxs = nil
}
